{% set name = "asciidoctor-reducer" %}
{% set version = "1.1.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 51df189807d820065060ff63873c577ab18388a21d4fc80ef7f98070600d5375
  - path: asciidoctor-reducer.bat

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - cp -v asciidoctor-reducer.bat $PREFIX/bin/asciidoctor-reducer.bat
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - asciidoctor >=2.0

test:
  commands:
    - asciidoctor-reducer -h

about:
  home: https://rubygems.org/gems/asciidoctor-reducer
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: A tool to generate a single AsciiDoc document by expanding all the include directives reachable from the parent document.

  doc_url: http://www.rubydoc.info/gems/asciidoctor-reducer
  dev_url: https://github.com/asciidoctor/asciidoctor-reducer

extra:
  recipe-maintainers:
    - ajaypnair09
